version: '3'
services:

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.8.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
	  
  redis:
    hostname: redis
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
      
  mongo:
    hostname: mongo
    image: mongo
    ports:
      - "27017:27017"      
